name: clox

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'jlox/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'jlox/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install build-essential
    - name: make
      run: (cd clox && make)
