name: clox

on:
  push:
    branches: [ "main" ]
    paths:
      - 'clox/**'
      - 'listoy/**'
      - '.github/workflows/clox.yml'
      - '!clox/**.md'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'clox/**'
      - 'listoy/**'
      - '.github/workflows/clox.yml'
      - '!clox/**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt install build-essential

    - name: Build & Test listoy
      run: (cd challenges/listoy && make && make test)

    - name: Build clox
      run: (cd clox && make)
